"""study plans

Revision ID: 161bc6c7553a
Revises: b6f17b0923d9
Create Date: 2026-08-08 00:29:45.328969

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "161bc6c7553a"
down_revision: str | None = "b6f17b0923d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study_plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("specialization_id", sa.String(length=64), nullable=False),
        sa.Column("interview_date", sa.Date(), nullable=False),
        sa.Column("target_grade", sa.SmallInteger(), nullable=False),
        sa.Column("daily_capacity", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("daily_capacity > 0", name=op.f("ck_study_plans_capacity_positive")),
        sa.CheckConstraint("target_grade BETWEEN 0 AND 6", name=op.f("ck_study_plans_grade_range")),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["specializations.id"],
            name=op.f("fk_study_plans_specialization_id_specializations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_study_plans_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_plans")),
    )
    op.create_index(
        "ix_study_plans_active",
        "study_plans",
        ["user_id", "specialization_id", "is_active"],
        unique=False,
    )
    op.create_table(
        "study_plan_days",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("day_index", sa.SmallInteger(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("topic_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("new_questions", sa.SmallInteger(), nullable=False),
        sa.Column("review_only", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["study_plans.id"],
            name=op.f("fk_study_plan_days_plan_id_study_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_plan_days")),
        sa.UniqueConstraint("plan_id", "day_index", name="plan_id_day_index"),
    )
    op.create_index("ix_study_plan_days_date", "study_plan_days", ["plan_id", "day"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_study_plan_days_date", table_name="study_plan_days")
    op.drop_table("study_plan_days")
    op.drop_index("ix_study_plans_active", table_name="study_plans")
    op.drop_table("study_plans")
    # ### end Alembic commands ###
