"""Таксономия: профессии, специализации, разделы, темы и веса разделов по грейдам.

Revision ID: 359aadb4ad93
Revises:
Create Date: 2026-08-07 23:37:25.167777

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "359aadb4ad93"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "professions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_professions")),
    )
    op.create_table(
        "specializations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("profession_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profession_id"],
            ["professions.id"],
            name=op.f("fk_specializations_profession_id_professions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_specializations")),
    )
    op.create_index(
        op.f("ix_specializations_profession_id"), "specializations", ["profession_id"], unique=False
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("specialization_id", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["specializations.id"],
            name=op.f("fk_topics_specialization_id_specializations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
        sa.UniqueConstraint("specialization_id", "code", name="specialization_id_code"),
    )
    op.create_index(
        op.f("ix_topics_specialization_id"), "topics", ["specialization_id"], unique=False
    )
    op.create_table(
        "subtopics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_subtopics_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subtopics")),
        sa.UniqueConstraint("topic_id", "code", name="topic_id_code"),
    )
    op.create_index(op.f("ix_subtopics_topic_id"), "subtopics", ["topic_id"], unique=False)
    op.create_table(
        "topic_weights",
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("grade", sa.SmallInteger(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.CheckConstraint("grade BETWEEN 0 AND 6", name=op.f("ck_topic_weights_grade_range")),
        sa.CheckConstraint(
            "weight >= 0 AND weight <= 1", name=op.f("ck_topic_weights_weight_range")
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_topic_weights_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("topic_id", "grade", name=op.f("pk_topic_weights")),
    )
    op.create_index("ix_topic_weights_grade", "topic_weights", ["grade"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_topic_weights_grade", table_name="topic_weights")
    op.drop_table("topic_weights")
    op.drop_index(op.f("ix_subtopics_topic_id"), table_name="subtopics")
    op.drop_table("subtopics")
    op.drop_index(op.f("ix_topics_specialization_id"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_specializations_profession_id"), table_name="specializations")
    op.drop_table("specializations")
    op.drop_table("professions")
    # ### end Alembic commands ###
