"""question reports

Revision ID: 5a229104b98f
Revises: 161bc6c7553a
Create Date: 2026-08-10 09:05:13.741781

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5a229104b98f"
down_revision: str | None = "161bc6c7553a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("specialization_id", sa.String(length=64), nullable=False),
        sa.Column("topic_code", sa.String(length=64), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("title_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("company", sa.String(length=128), nullable=True),
        sa.Column("asked_grade", sa.SmallInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "accepted",
                "rejected",
                "duplicate",
                name="report_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("moderation_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "asked_grade IS NULL OR asked_grade BETWEEN 0 AND 6",
            name=op.f("ck_question_reports_asked_grade_range"),
        ),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["specializations.id"],
            name=op.f("fk_question_reports_specialization_id_specializations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_question_reports_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_reports")),
        sa.UniqueConstraint("user_id", "title_fingerprint", name="user_id_title_fingerprint"),
    )
    op.create_index(
        "ix_question_reports_status", "question_reports", ["status", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_question_reports_user_id"), "question_reports", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_question_reports_user_id"), table_name="question_reports")
    op.drop_index("ix_question_reports_status", table_name="question_reports")
    op.drop_table("question_reports")
    # ### end Alembic commands ###
