"""questions

Revision ID: 6662d3224898
Revises: 359aadb4ad93
Create Date: 2026-08-07 23:58:09.794340

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6662d3224898"
down_revision: str | None = "359aadb4ad93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=96), nullable=False),
        sa.Column("topic_code", sa.String(length=64), nullable=False),
        sa.Column("subtopic_code", sa.String(length=64), nullable=True),
        sa.Column("min_grade", sa.SmallInteger(), nullable=False),
        sa.Column("peak_grade", sa.SmallInteger(), nullable=False),
        sa.Column("max_grade", sa.SmallInteger(), nullable=False),
        sa.Column("difficulty_rating", sa.SmallInteger(), nullable=False),
        sa.Column("frequency", sa.SmallInteger(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "single_choice",
                "multi_choice",
                "short_answer",
                "open_answer",
                name="question_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("answer_short", sa.Text(), nullable=False),
        sa.Column("answer_detailed", sa.Text(), nullable=False),
        sa.Column("common_mistakes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("follow_ups", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("company_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "seed",
                "crowdsourced",
                "imported",
                name="question_source",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("frequency BETWEEN 1 AND 5", name=op.f("ck_questions_frequency_range")),
        sa.CheckConstraint(
            "min_grade <= peak_grade AND peak_grade <= max_grade",
            name=op.f("ck_questions_grade_order"),
        ),
        sa.CheckConstraint(
            "min_grade BETWEEN 0 AND 6 AND peak_grade BETWEEN 0 AND 6 AND max_grade BETWEEN 0 AND 6",
            name=op.f("ck_questions_grade_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
        sa.UniqueConstraint("slug", name=op.f("uq_questions_slug")),
    )
    op.create_index("ix_questions_grades", "questions", ["min_grade", "max_grade"], unique=False)
    op.create_index("ix_questions_topic_code", "questions", ["topic_code"], unique=False)
    op.create_table(
        "question_options",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_question_options_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_options")),
        sa.UniqueConstraint("question_id", "code", name="question_id_code"),
    )
    op.create_index(
        op.f("ix_question_options_question_id"), "question_options", ["question_id"], unique=False
    )
    op.create_table(
        "question_specializations",
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("specialization_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_question_specializations_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["specializations.id"],
            name=op.f("fk_question_specializations_specialization_id_specializations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "question_id", "specialization_id", name=op.f("pk_question_specializations")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question_specializations")
    op.drop_index(op.f("ix_question_options_question_id"), table_name="question_options")
    op.drop_table("question_options")
    op.drop_index("ix_questions_topic_code", table_name="questions")
    op.drop_index("ix_questions_grades", table_name="questions")
    op.drop_table("questions")
    # ### end Alembic commands ###
