"""users, ratings, answers, review states

Revision ID: b6f17b0923d9
Revises: 6662d3224898
Create Date: 2026-08-08 00:09:55.466543

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b6f17b0923d9"
down_revision: str | None = "6662d3224898"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_premium", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "review_states",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("easiness_factor", sa.Float(), nullable=False),
        sa.Column("repetitions", sa.SmallInteger(), nullable=False),
        sa.Column("interval_days", sa.SmallInteger(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_review_states_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_review_states_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "question_id", name=op.f("pk_review_states")),
    )
    op.create_index("ix_review_states_due", "review_states", ["user_id", "due_at"], unique=False)
    op.create_table(
        "user_answers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("specialization_id", sa.String(length=64), nullable=False),
        sa.Column("topic_code", sa.String(length=64), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("selected_options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("free_text", sa.Text(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("quality", sa.SmallInteger(), nullable=False),
        sa.Column("rating_before", sa.Float(), nullable=False),
        sa.Column("rating_after", sa.Float(), nullable=False),
        sa.Column("difficulty_before", sa.SmallInteger(), nullable=False),
        sa.Column("difficulty_after", sa.SmallInteger(), nullable=False),
        sa.Column(
            "answered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quality BETWEEN 0 AND 5", name=op.f("ck_user_answers_quality_range")),
        sa.CheckConstraint("score >= 0 AND score <= 1", name=op.f("ck_user_answers_score_range")),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_user_answers_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["specializations.id"],
            name=op.f("fk_user_answers_specialization_id_specializations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_answers_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_answers")),
        sa.UniqueConstraint("user_id", "submission_id", name="user_id_submission_id"),
    )
    op.create_index(
        "ix_user_answers_user_question", "user_answers", ["user_id", "question_id"], unique=False
    )
    op.create_table(
        "user_specializations",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("specialization_id", sa.String(length=64), nullable=False),
        sa.Column("self_assessed_grade", sa.SmallInteger(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("answers_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "self_assessed_grade BETWEEN 0 AND 6", name=op.f("ck_user_specializations_grade_range")
        ),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["specializations.id"],
            name=op.f("fk_user_specializations_specialization_id_specializations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_specializations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "specialization_id", name=op.f("pk_user_specializations")
        ),
    )
    op.create_index(
        "ix_user_specializations_primary",
        "user_specializations",
        ["user_id", "is_primary"],
        unique=False,
    )
    op.create_table(
        "user_topic_ratings",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("specialization_id", sa.String(length=64), nullable=False),
        sa.Column("topic_code", sa.String(length=64), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("answers_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["specializations.id"],
            name=op.f("fk_user_topic_ratings_specialization_id_specializations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_topic_ratings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "specialization_id", "topic_code", name=op.f("pk_user_topic_ratings")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_topic_ratings")
    op.drop_index("ix_user_specializations_primary", table_name="user_specializations")
    op.drop_table("user_specializations")
    op.drop_index("ix_user_answers_user_question", table_name="user_answers")
    op.drop_table("user_answers")
    op.drop_index("ix_review_states_due", table_name="review_states")
    op.drop_table("review_states")
    op.drop_table("users")
    # ### end Alembic commands ###
